CREATE TABLE [dbo].[MEETING_SPEAKER]
(
	[MEETING_SPEAKER_ID]	INT IDENTITY NOT NULL 
								CONSTRAINT PK_MEETING_SPEAKER PRIMARY KEY CLUSTERED
,	[MEETING_ID]			INT NOT NULL
								CONSTRAINT FK_MEETING_SPEAKER_MEETING FOREIGN KEY (MEETING_ID) 
									REFERENCES dbo.MEETING(MEETING_ID)
,	[SPEAKER_ID]			INT NOT NULL
								CONSTRAINT FK_MEETING_SPEAKER_SPEAKER FOREIGN KEY (SPEAKER_ID) 
									REFERENCES dbo.SPEAKER(SPEAKER_ID)
)
