CREATE TABLE [dbo].[SPEAKER]
(
	[SPEAKER_ID]	INT IDENTITY NOT NULL 
						CONSTRAINT PK_SPEAKER PRIMARY KEY CLUSTERED
,	[PERSON_ID]		INT NOT NULL
						CONSTRAINT FK_SPEAKER_PERSON FOREIGN KEY
							(PERSON_ID) REFERENCES dbo.PERSON(PERSON_ID)
)
